### ISSUE TITLE
针对27的一个method swizzle问题

### ISSUE THREAD

**Issue by YanPengImp** [DarielChen/SwiftTips#2]
假如交换了一个UITableView和一个UIView中的方法，分别需要在这两个类的Extension中写awake函数，UIView是UITableView的父类，静态方法又不允许重写，就会有问题，有什么好的解决办法吗，想尝试用泛型去约束也没搞出来。（貌似在一个NSObject的Extension中实现协议的这个默认方法再添加@objc重写可以实现，但是感觉这样不优雅。）

**Comment by DarielChen** [comment]
让父类的`awake`方法调子类的`takeOnceTime`

**Comment by YanPengImp** [comment]
就是子类不用实现awake，全部通过父类去调用takeOnceTime，那以后万一替换的一个类又是之前某些类的父类，又要改变这些调用的地方了吗，岂不是更麻烦了

**Comment by DarielChen** [comment]
`又要改变这些调用的地方了吗`不是很明白啥意思,父类除了会调用子类的还会调用自己的`takeOnceTime `啊. 只是原来子类`26`的实现跟父类合并了

**Comment by YanPengImp** [comment]
假如最开始是替换的是UITableView和UIScrollView，UIScrollView是UITableView的父类，现在是在UIScrollView里面调用两个地方的takeOnceTime，那后面又加一个UIView，就需要把这些移动到UIView中去了吧，我的理解是这样。因为awake方法只能在最高的那个父类里面去实现吧。能否出个demo演示一下这种。

**Comment by DarielChen** [comment]
对的,`awake`放到最高类中
```swift
class ChildButton: UIButton {
}
extension ChildButton {
    static let takeOnceTime: Void = {
        // 子类的交换方法实现
    }()
}
extension UIButton: SelfAware {
    static func awake() {
        UIButton.takeOnceTime
        ChildButton.takeOnceTime
    }
    private static let takeOnceTime: Void = {
        // 父类的交换方法实现
    }()
}
```

**Comment by YanPengImp** [comment]
就是这种，然后如果后面加个UIControl或者UIView的Extension，就需要把awake移到这个父类里面去了，如果在多人协同工作下，是不是太麻烦了，因为可能每个人需求不一样，后期需要替换的类越来越多，也不太容易管理吧，感觉会导致各个业务之间有耦合了。不像OC中每一个文件或者一个category管理一个业务的替换，各自不会影响。

**Comment by DarielChen** [comment]
那你参照`15`吧
