### ISSUE TITLE
enum调用静态方法和struct调用静态方法有什么不同呢？

### ISSUE THREAD

**Issue by eppeo** [DarielChen/SwiftTips#3]
我看你代码中习惯这样定义一个静态方法(11.华丽的tableView中第二条)
enum AnimationFactory {
    static func makeFade() {
         //TODO:
     }
}
一般我这样写都是声明为struct类型，不知道声明成enum类型是出于性能考虑还是个人喜好？

**Comment by DarielChen** [comment]
用struct也可以，但struct是结构化的数据类型。这边`AnimationFactory`中的几个方法之间没有结构化的关系，更多的是类似case一样的操作，所以我觉得用enum更合理一点
