### ISSUE TITLE
tip 26 现在还是有效的吗？

### ISSUE THREAD

**Issue by rakuyoMo** [DarielChen/SwiftTips#5]
Swift 5.x + iOS 13.x。`UIApplication` 的 `next` 方法在 `didFinishLaunchingWithOptions` 方法之后调用...

**Comment by DarielChen** [comment]
那还是用OC转一下吧，这种方式有被覆盖的可能

**Comment by rakuyoMo** [comment]
> 那还是用OC转一下吧，这种方式有被覆盖的可能

好像也不止我遇到了这个问题，有一位朋友今天在升级 Xcode 到最新之后也出现了我所描述的问题.... 目前还没有解决办法， 也不清楚原因是什么

主要是我想用 `+load` 方法的那个特性，用 OC 转实在是不方便...

我在 stackoverflow 上提了[这个问题](https://stackoverflow.com/questions/60970783/uiapplications-next-method-is-executed-in-the-wrong-order)，希望能找到答案

**Comment by rakuyoMo** [comment]
我在 stackoverflow 上提了[这个问题](https://stackoverflow.com/questions/60970783/uiapplications-next-method-is-executed-in-the-wrong-order)，希望能找到答案
